//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__fileStrin__lang___24927208", "lang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.lang), "fileStringData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.fileStringData), true)]
[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__fileStrin__proje__239E4DCF", "project", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.project), "fileStringData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.fileStringData), true)]
[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__fileStrin__resou__25869641", "resourceFile", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.resourceFile), "fileStringData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.fileStringData), true)]
[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__lang__project_id__145C0A3F", "project", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.project), "lang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.lang), true)]
[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__stringDat__lang___1CF15040", "lang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.lang), "stringData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.stringData), true)]
[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__resourceF__proje__1FCDBCEB", "project", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.project), "resourceFile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.resourceFile), true)]
[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__resxItem__projec__182C9B23", "project", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.project), "resxItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.resxItem), true)]
[assembly: EdmRelationshipAttribute("ResourceStringManagerModel", "FK__stringDat__resxI__1BFD2C07", "resxItem", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(i18nEntities.resxItem), "stringData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(i18nEntities.stringData), true)]

#endregion

namespace i18nEntities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ResourceStringManagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ResourceStringManagerEntities object using the connection string found in the 'ResourceStringManagerEntities' section of the application configuration file.
        /// </summary>
        public ResourceStringManagerEntities() : base("name=ResourceStringManagerEntities", "ResourceStringManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ResourceStringManagerEntities object.
        /// </summary>
        public ResourceStringManagerEntities(string connectionString) : base(connectionString, "ResourceStringManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ResourceStringManagerEntities object.
        /// </summary>
        public ResourceStringManagerEntities(EntityConnection connection) : base(connection, "ResourceStringManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<fileStringData> fileStringDatas
        {
            get
            {
                if ((_fileStringDatas == null))
                {
                    _fileStringDatas = base.CreateObjectSet<fileStringData>("fileStringDatas");
                }
                return _fileStringDatas;
            }
        }
        private ObjectSet<fileStringData> _fileStringDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lang> langs
        {
            get
            {
                if ((_langs == null))
                {
                    _langs = base.CreateObjectSet<lang>("langs");
                }
                return _langs;
            }
        }
        private ObjectSet<lang> _langs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<project> projects
        {
            get
            {
                if ((_projects == null))
                {
                    _projects = base.CreateObjectSet<project>("projects");
                }
                return _projects;
            }
        }
        private ObjectSet<project> _projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<resourceFile> resourceFiles
        {
            get
            {
                if ((_resourceFiles == null))
                {
                    _resourceFiles = base.CreateObjectSet<resourceFile>("resourceFiles");
                }
                return _resourceFiles;
            }
        }
        private ObjectSet<resourceFile> _resourceFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<resxItem> resxItems
        {
            get
            {
                if ((_resxItems == null))
                {
                    _resxItems = base.CreateObjectSet<resxItem>("resxItems");
                }
                return _resxItems;
            }
        }
        private ObjectSet<resxItem> _resxItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stringData> stringDatas
        {
            get
            {
                if ((_stringDatas == null))
                {
                    _stringDatas = base.CreateObjectSet<stringData>("stringDatas");
                }
                return _stringDatas;
            }
        }
        private ObjectSet<stringData> _stringDatas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the fileStringDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofileStringDatas(fileStringData fileStringData)
        {
            base.AddObject("fileStringDatas", fileStringData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the langs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolangs(lang lang)
        {
            base.AddObject("langs", lang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprojects(project project)
        {
            base.AddObject("projects", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the resourceFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresourceFiles(resourceFile resourceFile)
        {
            base.AddObject("resourceFiles", resourceFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the resxItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresxItems(resxItem resxItem)
        {
            base.AddObject("resxItems", resxItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stringDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostringDatas(stringData stringData)
        {
            base.AddObject("stringDatas", stringData);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResourceStringManagerModel", Name="fileStringData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fileStringData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new fileStringData object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static fileStringData CreatefileStringData(global::System.Int32 id)
        {
            fileStringData fileStringData = new fileStringData();
            fileStringData.id = id;
            return fileStringData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> project_id
        {
            get
            {
                return _project_id;
            }
            set
            {
                Onproject_idChanging(value);
                ReportPropertyChanging("project_id");
                _project_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("project_id");
                Onproject_idChanged();
            }
        }
        private Nullable<global::System.Int32> _project_id;
        partial void Onproject_idChanging(Nullable<global::System.Int32> value);
        partial void Onproject_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lang_id
        {
            get
            {
                return _lang_id;
            }
            set
            {
                Onlang_idChanging(value);
                ReportPropertyChanging("lang_id");
                _lang_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lang_id");
                Onlang_idChanged();
            }
        }
        private Nullable<global::System.Int32> _lang_id;
        partial void Onlang_idChanging(Nullable<global::System.Int32> value);
        partial void Onlang_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> resourceFile_id
        {
            get
            {
                return _resourceFile_id;
            }
            set
            {
                OnresourceFile_idChanging(value);
                ReportPropertyChanging("resourceFile_id");
                _resourceFile_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("resourceFile_id");
                OnresourceFile_idChanged();
            }
        }
        private Nullable<global::System.Int32> _resourceFile_id;
        partial void OnresourceFile_idChanging(Nullable<global::System.Int32> value);
        partial void OnresourceFile_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resourcekey
        {
            get
            {
                return _resourcekey;
            }
            set
            {
                OnresourcekeyChanging(value);
                ReportPropertyChanging("resourcekey");
                _resourcekey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resourcekey");
                OnresourcekeyChanged();
            }
        }
        private global::System.String _resourcekey;
        partial void OnresourcekeyChanging(global::System.String value);
        partial void OnresourcekeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.String _data;
        partial void OndataChanging(global::System.String value);
        partial void OndataChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__fileStrin__lang___24927208", "lang")]
        public lang lang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lang>("ResourceStringManagerModel.FK__fileStrin__lang___24927208", "lang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lang>("ResourceStringManagerModel.FK__fileStrin__lang___24927208", "lang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lang> langReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lang>("ResourceStringManagerModel.FK__fileStrin__lang___24927208", "lang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lang>("ResourceStringManagerModel.FK__fileStrin__lang___24927208", "lang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__fileStrin__proje__239E4DCF", "project")]
        public project project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__fileStrin__proje__239E4DCF", "project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__fileStrin__proje__239E4DCF", "project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<project> projectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__fileStrin__proje__239E4DCF", "project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<project>("ResourceStringManagerModel.FK__fileStrin__proje__239E4DCF", "project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__fileStrin__resou__25869641", "resourceFile")]
        public resourceFile resourceFile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resourceFile>("ResourceStringManagerModel.FK__fileStrin__resou__25869641", "resourceFile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resourceFile>("ResourceStringManagerModel.FK__fileStrin__resou__25869641", "resourceFile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<resourceFile> resourceFileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resourceFile>("ResourceStringManagerModel.FK__fileStrin__resou__25869641", "resourceFile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<resourceFile>("ResourceStringManagerModel.FK__fileStrin__resou__25869641", "resourceFile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResourceStringManagerModel", Name="lang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lang object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static lang Createlang(global::System.Int32 id)
        {
            lang lang = new lang();
            lang.id = id;
            return lang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> project_id
        {
            get
            {
                return _project_id;
            }
            set
            {
                Onproject_idChanging(value);
                ReportPropertyChanging("project_id");
                _project_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("project_id");
                Onproject_idChanged();
            }
        }
        private Nullable<global::System.Int32> _project_id;
        partial void Onproject_idChanging(Nullable<global::System.Int32> value);
        partial void Onproject_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private global::System.String _code;
        partial void OncodeChanging(global::System.String value);
        partial void OncodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String desc
        {
            get
            {
                return _desc;
            }
            set
            {
                OndescChanging(value);
                ReportPropertyChanging("desc");
                _desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("desc");
                OndescChanged();
            }
        }
        private global::System.String _desc;
        partial void OndescChanging(global::System.String value);
        partial void OndescChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__fileStrin__lang___24927208", "fileStringData")]
        public EntityCollection<fileStringData> fileStringDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fileStringData>("ResourceStringManagerModel.FK__fileStrin__lang___24927208", "fileStringData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fileStringData>("ResourceStringManagerModel.FK__fileStrin__lang___24927208", "fileStringData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__lang__project_id__145C0A3F", "project")]
        public project project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__lang__project_id__145C0A3F", "project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__lang__project_id__145C0A3F", "project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<project> projectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__lang__project_id__145C0A3F", "project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<project>("ResourceStringManagerModel.FK__lang__project_id__145C0A3F", "project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__stringDat__lang___1CF15040", "stringData")]
        public EntityCollection<stringData> stringDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stringData>("ResourceStringManagerModel.FK__stringDat__lang___1CF15040", "stringData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stringData>("ResourceStringManagerModel.FK__stringDat__lang___1CF15040", "stringData", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResourceStringManagerModel", Name="project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new project object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static project Createproject(global::System.Int32 id)
        {
            project project = new project();
            project.id = id;
            return project;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String outputdir
        {
            get
            {
                return _outputdir;
            }
            set
            {
                OnoutputdirChanging(value);
                ReportPropertyChanging("outputdir");
                _outputdir = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("outputdir");
                OnoutputdirChanged();
            }
        }
        private global::System.String _outputdir;
        partial void OnoutputdirChanging(global::System.String value);
        partial void OnoutputdirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String outputfilename
        {
            get
            {
                return _outputfilename;
            }
            set
            {
                OnoutputfilenameChanging(value);
                ReportPropertyChanging("outputfilename");
                _outputfilename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("outputfilename");
                OnoutputfilenameChanged();
            }
        }
        private global::System.String _outputfilename;
        partial void OnoutputfilenameChanging(global::System.String value);
        partial void OnoutputfilenameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__fileStrin__proje__239E4DCF", "fileStringData")]
        public EntityCollection<fileStringData> fileStringDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fileStringData>("ResourceStringManagerModel.FK__fileStrin__proje__239E4DCF", "fileStringData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fileStringData>("ResourceStringManagerModel.FK__fileStrin__proje__239E4DCF", "fileStringData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__lang__project_id__145C0A3F", "lang")]
        public EntityCollection<lang> langs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lang>("ResourceStringManagerModel.FK__lang__project_id__145C0A3F", "lang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lang>("ResourceStringManagerModel.FK__lang__project_id__145C0A3F", "lang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__resourceF__proje__1FCDBCEB", "resourceFile")]
        public EntityCollection<resourceFile> resourceFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<resourceFile>("ResourceStringManagerModel.FK__resourceF__proje__1FCDBCEB", "resourceFile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<resourceFile>("ResourceStringManagerModel.FK__resourceF__proje__1FCDBCEB", "resourceFile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__resxItem__projec__182C9B23", "resxItem")]
        public EntityCollection<resxItem> resxItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<resxItem>("ResourceStringManagerModel.FK__resxItem__projec__182C9B23", "resxItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<resxItem>("ResourceStringManagerModel.FK__resxItem__projec__182C9B23", "resxItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResourceStringManagerModel", Name="resourceFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resourceFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new resourceFile object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static resourceFile CreateresourceFile(global::System.Int32 id)
        {
            resourceFile resourceFile = new resourceFile();
            resourceFile.id = id;
            return resourceFile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> project_id
        {
            get
            {
                return _project_id;
            }
            set
            {
                Onproject_idChanging(value);
                ReportPropertyChanging("project_id");
                _project_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("project_id");
                Onproject_idChanged();
            }
        }
        private Nullable<global::System.Int32> _project_id;
        partial void Onproject_idChanging(Nullable<global::System.Int32> value);
        partial void Onproject_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resx_filepath
        {
            get
            {
                return _resx_filepath;
            }
            set
            {
                Onresx_filepathChanging(value);
                ReportPropertyChanging("resx_filepath");
                _resx_filepath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resx_filepath");
                Onresx_filepathChanged();
            }
        }
        private global::System.String _resx_filepath;
        partial void Onresx_filepathChanging(global::System.String value);
        partial void Onresx_filepathChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__fileStrin__resou__25869641", "fileStringData")]
        public EntityCollection<fileStringData> fileStringDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fileStringData>("ResourceStringManagerModel.FK__fileStrin__resou__25869641", "fileStringData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fileStringData>("ResourceStringManagerModel.FK__fileStrin__resou__25869641", "fileStringData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__resourceF__proje__1FCDBCEB", "project")]
        public project project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__resourceF__proje__1FCDBCEB", "project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__resourceF__proje__1FCDBCEB", "project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<project> projectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__resourceF__proje__1FCDBCEB", "project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<project>("ResourceStringManagerModel.FK__resourceF__proje__1FCDBCEB", "project", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResourceStringManagerModel", Name="resxItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resxItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new resxItem object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static resxItem CreateresxItem(global::System.Int32 id)
        {
            resxItem resxItem = new resxItem();
            resxItem.id = id;
            return resxItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> project_id
        {
            get
            {
                return _project_id;
            }
            set
            {
                Onproject_idChanging(value);
                ReportPropertyChanging("project_id");
                _project_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("project_id");
                Onproject_idChanged();
            }
        }
        private Nullable<global::System.Int32> _project_id;
        partial void Onproject_idChanging(Nullable<global::System.Int32> value);
        partial void Onproject_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resourcekey
        {
            get
            {
                return _resourcekey;
            }
            set
            {
                OnresourcekeyChanging(value);
                ReportPropertyChanging("resourcekey");
                _resourcekey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resourcekey");
                OnresourcekeyChanged();
            }
        }
        private global::System.String _resourcekey;
        partial void OnresourcekeyChanging(global::System.String value);
        partial void OnresourcekeyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__resxItem__projec__182C9B23", "project")]
        public project project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__resxItem__projec__182C9B23", "project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__resxItem__projec__182C9B23", "project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<project> projectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("ResourceStringManagerModel.FK__resxItem__projec__182C9B23", "project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<project>("ResourceStringManagerModel.FK__resxItem__projec__182C9B23", "project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__stringDat__resxI__1BFD2C07", "stringData")]
        public EntityCollection<stringData> stringDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stringData>("ResourceStringManagerModel.FK__stringDat__resxI__1BFD2C07", "stringData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stringData>("ResourceStringManagerModel.FK__stringDat__resxI__1BFD2C07", "stringData", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResourceStringManagerModel", Name="stringData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stringData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stringData object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static stringData CreatestringData(global::System.Int32 id)
        {
            stringData stringData = new stringData();
            stringData.id = id;
            return stringData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> resxItem_id
        {
            get
            {
                return _resxItem_id;
            }
            set
            {
                OnresxItem_idChanging(value);
                ReportPropertyChanging("resxItem_id");
                _resxItem_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("resxItem_id");
                OnresxItem_idChanged();
            }
        }
        private Nullable<global::System.Int32> _resxItem_id;
        partial void OnresxItem_idChanging(Nullable<global::System.Int32> value);
        partial void OnresxItem_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lang_id
        {
            get
            {
                return _lang_id;
            }
            set
            {
                Onlang_idChanging(value);
                ReportPropertyChanging("lang_id");
                _lang_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lang_id");
                Onlang_idChanged();
            }
        }
        private Nullable<global::System.Int32> _lang_id;
        partial void Onlang_idChanging(Nullable<global::System.Int32> value);
        partial void Onlang_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.String _data;
        partial void OndataChanging(global::System.String value);
        partial void OndataChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__stringDat__lang___1CF15040", "lang")]
        public lang lang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lang>("ResourceStringManagerModel.FK__stringDat__lang___1CF15040", "lang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lang>("ResourceStringManagerModel.FK__stringDat__lang___1CF15040", "lang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lang> langReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lang>("ResourceStringManagerModel.FK__stringDat__lang___1CF15040", "lang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lang>("ResourceStringManagerModel.FK__stringDat__lang___1CF15040", "lang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResourceStringManagerModel", "FK__stringDat__resxI__1BFD2C07", "resxItem")]
        public resxItem resxItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resxItem>("ResourceStringManagerModel.FK__stringDat__resxI__1BFD2C07", "resxItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resxItem>("ResourceStringManagerModel.FK__stringDat__resxI__1BFD2C07", "resxItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<resxItem> resxItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<resxItem>("ResourceStringManagerModel.FK__stringDat__resxI__1BFD2C07", "resxItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<resxItem>("ResourceStringManagerModel.FK__stringDat__resxI__1BFD2C07", "resxItem", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
